export const LOGIN_START = "LOGIN_START"
export const LOGIN_SUCCESS = "LOGIN_SUCCESS"
export const LOGIN_ERROR = "LOGIN_ERROR"

export const INVENORY_DATA_START = "INVENORY_DATA_START"
export const INVENORY_DATA_SUCCESS = "INVENORY_DATA_SUCCESS"
export const INVENORY_DATA_ERROR = "INVENORY_DATA_ERROR"

export const CHANGE_PASSWORD_DATA_START = "CHANGE_PASSWORD_DATA_START"
export const CHANGE_PASSWORD_DATA_SUCCESS = "CHANGE_PASSWORD_DATA_SUCCESS"
export const CHANGE_PASSWORD_DATA_ERROR = "CHANGE_PASSWORD_DATA_ERROR"